# Generated by Django 3.1.7 on 2022-12-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('comment', models.TextField()),
            ],
        ),
    ]
