# Generated by Django 3.1.7 on 2022-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
