# Generated by Django 3.1.7 on 2023-01-02 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0003_padlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='padlet',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000000000000000000000000000000000000000000000),
            preserve_default=False,
        ),
    ]
