# Generated by Django 3.1.7 on 2023-01-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0004_padlet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padlet',
            name='img',
            field=models.CharField(max_length=1000000000),
        ),
    ]
